---
title: "Ανάλυση Νοσοκομειακών Δεδομένων 2022"
author: "Silia Georgaki"
format:
  html:
    toc: true
    toc-location: left
    code-fold: true
    embed-resources: true
    fig-width: 8
    fig-height: 4
execute:
  warning: false
jupyter: python3
---

# Περίληψη

Η αξιολόγηση και ο έλεγχος της λειτουργίας των νοσοκομείων είναι απαραίτητα τόσο για την ποιότητα των υπηρεσιών υγειονομικής περίθαλψης όσο και για την οικονομία της χώρας. Ένας αποδοτικός και αξιόπιστος τρόπος αξιολόγησης των συστημάτων υγείας είναι μέσω των βασικών δεικτών απόδοσης (KPIs). Με την αξιοποίηση αυτών εντοπίζονται κενά στην ποιότητα ή την αποτελεσματικότητα των νοσοκομείων και έτσι είναι δυνατή η αξιολόγηση της λειτουργίας τους. Ο κύριος στόχος της παρούσας μελέτης είναι ο υπολογισμός και η  ανάλυση των οικονομικών και λειτουργικών δεικτών στα νοσοκομεία όλων των  υγειονομικής περίθαλψης Περιφερειών της Ελλάδας. Έτσι, θα εξαχθούν συμπεράσματα για την ομαλή ή μη λειτουργία τους. 

*Λέξεις-κλειδιά:* Νοσοκομειακά δεδομένα, βασικοί δείκτες απόδοσης, ηλεκτρονική υγεία.

# Abstract

Evaluation and monitoring of hospital operations are essential for both the quality of health care services and the country's economy. An efficient and reliable 
way of evaluating health systems is through key performance indicators (KPIs). By using these, gaps in the quality or efficiency of hospitals can be identified and thus it is possible to evaluate their operation. The main objective of this study is to calculate and analyze the financial and operational indicators in hospitals in all healthcare regions of Greece. Thus, conclusions will be drawn about their smooth or not functioning.

*Keywords:* Hospital data, key performance indicators, e-health.

# Εισαγωγή

Η υγεία, πόσο μάλλον η δημόσια υγεία είναι ένα αγαθό το οποίο χρειάζεται προσεκτική διαχείριση. Τα τελευταία χρόνια, έχουν αναζητηθεί διάφορες μέθοδοι για να εξασφαλιστεί η σωστή απόδοση των νοσοκομείων και η βελτίωση της αποτελεσματικότητάς τους παγκοσμίως, αλλά και στην Ελλάδα. Το γεγονός αυτό οδήγησε πράγματι σε μία καλύτερη δημόσια υγεία. Πάραυτα, τα συστήματα υγείας πολλών χωρών εξακολουθούν να παρουσιάζουν αδυναμίες. Στην Ελλάδα, μία από τις μεθόδους παρακολούθησης της λειτουργίας των νοσοκομείων είναι με συγκεκριμένους δείκτες (KPIs). Αυτοί χωρίζονται σε δύο κύριες κατηγορίες: λειτουργικούς δείκτες και οικονομικούς δείκτες. Οι λειτουργικοί δείκτες δηλώνουν την ομαλή ή μη λειτουργία του νοσοκομείου όσον αφορά την διαχείριση ασθενών, των κλινών κ.α. ενώ οι οικονομικοί δείκτες δηλώνουν την ομαλή ή μη διαχείριση των οικονομικών πόρων του νοσοκομείου. 

# Δεδομένα

Για τον υπολογισμό των δεικτών αξιοποιήθηκαν δεδομένα από το Ε.Σ.Υ. για το έτος 2022. Συγκεκριμένα, υπήρχαν δεδομένα για κάθε υγειονομική περιφέρεια αναφορικά με τις κλίνες, τους εσωτερικούς και τους εξωτερικούς ασθενείς, τα έξοδα για τα αναλώσιμα και τις υπηρεσίες κ.α. Ωστόσο, λόγω απώλειας κάποιων δεδομένων, δεν ήταν δυνατός ο υπολογισμός όλων των δεικτών και έτσι χρησιμοποιήθηκαν δεδομένα αναφορικά με:

*	Όνομα νοσοκομείου
*	Κατηγορία νοσοκομείου
*	Αριθμός κλινών
*	Αριθμός Νοσηλευθέντων
*	Ημέρες Νοσηλείας
*	Μισθοδοσία (αμοιβές επικουρικού)
*	Μισθοδοσία (πρόσθετες αμοιβές)
*	Δ.Ε.Κ.Ο
*	Ασφάλεια
*	Καθαριότητα
*	Εστίαση
*	Υπόλοιπα
*	Σύνολο

Με την αξιοποίηση αυτώ των δεδομένων, υπολογίστηκαν οι δείκτες:

*	Μέση Διάρκεια Νοσηλείας
*	Πληρότητα Κλινών
*	Ρυθμός Εναλλαγής Κλινών
*	Μέσο Συνολικό Κόστος Ασθενή
*	Μέσο Κόστος Υπηρεσιών ανά Ημέρα Νοσηλείας
*	Συνολικό Ποσοστό Υπηρεσιών
*	Ποσοστό Συνολικών Εξωτερικών Υπηρεσιών
*	Μέσο Μηνιαίο Κόστος των Εξωτερικών Υπηρεσιών ανά Κλίνη
*	Μέσο Κόστος των Εξωτερικών Υπηρεσιών ανά Ασθενή


# Φόρτωση πακέτων

```{python}
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import openpyxl
```

# Λειτουργικοί Δείκτες

## Μέση Διάρκεια Νοσηλείας

Γενικά η μέση διάρκεια νοσηλείας θεωρείται αποτελεσματικός δείκτης καθώς μία μικρότερη διάρκεια νοσηλείας σημαίνει και λιγότερες δαπάνες. Είναι ωστόσο σημαντικό να τονιστεί πως ένας πολύ χαμηλός δείκτης μέσης διάρκειας νοσηλείας μπορεί να υποδηλώνει αναποτελεσματικότητα. Αυτό γιατί η ποιότητα των υπηρεσιών ενδέχεται να είναι χαμηλή και άρα ο ασθενής να χρειαστεί επαναεισαγωγή. Σε αυτό το σημείο αξίζει να τονιστεί πως τα αποτελέσματα δε μπορούν να εξαχθούν εύκολα με συγκρίσεις γιατί το κάθε νοσοκομείο έχει διαφορετικό αριθμό κλινών.

```{python}
# Read the Excel file
als = pd.read_excel('operational.xlsx', sheet_name = 'Μέση Διάρκεια Νοσηλείας')

# Group the data by hospital type
grouped_data = als.groupby('ΚΑΤΗΓΟΡΙΑ ΝΟΣΟΚΟΜΕΙΟΥ')

# Get the unique hospital types
hospital_types = als['ΚΑΤΗΓΟΡΙΑ ΝΟΣΟΚΟΜΕΙΟΥ'].unique()

# Create a subplot for each hospital type
fig, axs = plt.subplots(len(hospital_types), 1, figsize = (8, 6 * len(hospital_types)))

# Iterate over hospital types and create bar plots
for i, hospital_type in enumerate(hospital_types):
    data = grouped_data.get_group(hospital_type)
    ax = axs[i]
    ax.bar(data['ΝΟΣΟΚΟΜΕΙΟ'], data['ΜΕΣΗ ΔΙΑΡΚΕΙΑ ΝΟΣΗΛΕΙΑΣ'], color = '#9EBBC4')
    ax.set_title(f'Κατηγορία Νοσοκομείου: {hospital_type}')
    ax.set_xlabel('Νοσοκομείο')
    ax.set_ylabel('Μέση Διάρκεια Νοσηλείας')
    ax.tick_params(axis = 'x', rotation = 90, labelsize = 6)  # Rotate and resize x-axis labels

# Adjust the layout
plt.tight_layout()

# Display the plot
plt.show()
```

Το Γενικό Νοσοκομείο Κατερίνης έχει τον υψηλότερο δείκτη ενώ το Γ.Ν. Δυτικής Αττικής και το Γ.Ν. ΛΗΞΟΥΡΙΟΥ "ΜΑΝΤΖΑΒΙΝΑΤΕΙΟ" έχουν τους χαμηλότερους. Ο αριθμός των κλινών είναι 387, 58 και 5 αντίστοιχα. Τα δύο τελευταία ανήκουν και στην ίδια κατηγορία επομένως η απόδοση είναι φυσιολογική. Όσον αφορά το Γενικό Νοσοκομείο Κατερίνης, παρατηρούμε από τα δεδομένα ότι δεν έχει τον μέγιστο αριθμό κλινών από τα γενικά νοσοκομεία. Ακόμα, ενώ στις περισσότερες κατηγορίες νοσοκομείων δεν παρατηρούνται σημαντικές διαφορές, στα Γ.Ν.-Κ.Υ. παρατηρείται μεγάλη διαφορά στον υψηλό δείκτη του Γ.Ν.-Κ.Υ. Γουμενίτσας με τον χαμηλό δείκτη του Γ.Ν.-Κ.Υ. Κρεστενών. Ο αριθμός κλινών είναι 25 και 10 αντίστοιχα.

## Πληρότητα κλινών

Η πληρότητα κλινών πολλές φορές χρησιμοποιείται και ως τρόπο σύγκρισης διαχείρισης των πόρων. Ενώ γενικά ο υψηλός αυτός δείκτης μπορεί να σημαίνει αποτελεσματικότητα του νοσοκομείου, εξαρτάται άμεσα και από την διάρκεια παραμονής του ασθενούς στο νοσοκομείο. 

```{python}
# Read the Excel file
bed_occupancy = pd.read_excel('operational.xlsx', sheet_name = 'Πληρότητα Κλινών')

# Group the data by hospital type
grouped_data = bed_occupancy.groupby('ΚΑΤΗΓΟΡΙΑ ΝΟΣΟΚΟΜΕΙΟΥ')

# Get the unique hospital types
hospital_types = bed_occupancy['ΚΑΤΗΓΟΡΙΑ ΝΟΣΟΚΟΜΕΙΟΥ'].unique()

# Create a subplot for each hospital type
fig, axs = plt.subplots(len(hospital_types), 1, figsize = (8, 6 * len(hospital_types)))

# Iterate over hospital types and create bar plots
for i, hospital_type in enumerate(hospital_types):
    data = grouped_data.get_group(hospital_type)
    ax = axs[i]
    ax.bar(data['ΝΟΣΟΚΟΜΕΙΟ'], data['ΠΛΗΡΟΤΗΤΑ ΚΛΙΝΩΝ'], color = '#9EBBC4')
    ax.set_title(f'Κατηγορία Νοσοκομείου: {hospital_type}')
    ax.set_xlabel('Νοσοκομείο')
    ax.set_ylabel('Πληρότητα Κλινών (%)')
    ax.tick_params(axis = 'x', rotation = 90, labelsize = 6)  # Rotate and resize x-axis labels
    ax.set_ylim(0, 1)  # Set the y-axis limits to 0-1 for percentage values

    # Set y-axis tick labels as percentages
    ax.yaxis.set_major_formatter('{x:.0%}')

# Adjust the layout
plt.tight_layout()

# Display the plot
plt.show()
```

Όσον αφορά τα γενικά νοσοκομεία, παρατηρείται γενικότερα πως ο δείκτης δεν διαφέρει κατά πολύ ανά νοσοκομείο. Ωστόσο, δύο νοσοκομεία παρουσιάζουν πολύ χαμηλό δείκτη. Αυτά είναι το Γενικό Νοσοκομείο Δυτικής Αττικής και το Γενικό Νοσοκομείο Αμαλιάδας με αριθμό κλινών 58 και 86 αντίστοιχα. Φαίνεται ο αριθμός των κλινών να μην είναι κυρίαρχος παράγοντας διότι νοσοκομεία με εξίσου χαμηλό αριθμό κλινών είχαν καλύτερη απόδοση. Ακόμα, παρά το γεγονός ότι το Γ.Ν. Αμαλιάδας έχει περισσότερες κλίνες από το Γ.Ν. Δυτικής Αττικής, παρουσιάζει χαμηλότερο δείκτη. Επίσης, παρατηρείται έντονη διαφορά μεταξύ των Μαιευτικών νοσοκομείων. Η διαφορά αυτή οφείλεται στην μεγάλη διαφορά του αριθμού κλινών. Αναφορικά με τα Γ.Ν.-Κ.Υ, και σε αυτή τη περίπτωση το Γ.Ν.-Κ.Υ. Κρεστενών παρουσιάζει τον χαμηλότερο δείκτη, διαθέτοντας όμως μόλις 10 κλίνες. Στα υπόλοιπα νοσοκομεία δεν υπήρχε μεγάλη απόκλιση στις τιμές του δείκτη με εξαίρεση το οφθαλμολογικό που ξεπερνούσε το 100% και κάποια πανεπιστημιακά που ξεπερνούσαν επίσης το 100%.

## Ρυθμός Εναλλαγής κλινών - Διάστημα Εναλλαγής Κλινών

Ο ρυθμός εναλλαγής κλινών δηλώνει το πλήθος των εναλλαγών του ασθενούς σε ένα κρεβάτι και το διάστημα εναλλαγής κλινών μετρά τον χρόνο διαθεσιμότητας των συνολικών κρεβατιών. 


```{python}
# Read the Excel file
bed_turnover = pd.read_excel('operational.xlsx', sheet_name ='Ρυθμός Εναλλαγής Κλινών')

# Group the data by hospital type
grouped_data = bed_turnover.groupby('ΚΑΤΗΓΟΡΙΑ ΝΟΣΟΚΟΜΕΙΟΥ')

# Get the unique hospital types
hospital_types = bed_turnover['ΚΑΤΗΓΟΡΙΑ ΝΟΣΟΚΟΜΕΙΟΥ'].unique()

# Create a subplot for each hospital type
fig, axs = plt.subplots(len(hospital_types), 2, figsize = (12, 6 * len(hospital_types)))

# Iterate over hospital types and create bar plots
for i, hospital_type in enumerate(hospital_types):
    data = grouped_data.get_group(hospital_type)
    ax1 = axs[i][0]
    ax2 = axs[i][1]
    
    # Plot bed turnover rate
    ax1.bar(data.index, data['ΡΥΘΜΟΣ ΕΝΑΛΛΑΓΗΣ ΚΛΙΝΩΝ'], color = '#9EBBC4')
    ax1.set_ylabel('Ρυθμός Εναλλαγής Κλινών')
    ax1.set_xticks(data.index)
    ax1.set_xticklabels(data['ΝΟΣΟΚΟΜΕΙΟ'], rotation = 90, ha = 'right', fontsize = 4)
    ax1.set_title(f'Κατηγορία Νοσοκομείου: {hospital_type}')
    ax1.set_ylim(0, data['ΡΥΘΜΟΣ ΕΝΑΛΛΑΓΗΣ ΚΛΙΝΩΝ'].max() * 1.1)  # Set consistent y-axis range
    
    # Plot bed turnover interval
    ax2.bar(data.index, data['ΔΙΑΣΤΗΜΑ ΕΝΑΛΛΑΓΗΣ ΚΛΙΝΩΝ'], color='#9EBBC4')
    ax2.set_ylabel('Διάστημα Εναλλαγής Κλινών')
    ax2.set_xticks(data.index)
    ax2.set_xticklabels(data['ΝΟΣΟΚΟΜΕΙΟ'], rotation = 90, ha = 'right', fontsize = 4)
    ax2.set_title(f'Κατηγορία Νοσοκομείου: {hospital_type}')
    ax2.set_ylim(0, data['ΔΙΑΣΤΗΜΑ ΕΝΑΛΛΑΓΗΣ ΚΛΙΝΩΝ'].max() * 1.1)  # Set consistent y-axis range
    
plt.tight_layout()
plt.show()
```

Αναφορικά με τα Γενικά νοσοκομεία και οι δύο δείκτες παρουσιάζουν έντονες διαφορές. Ωστόσο, για τον ρυθμό εναλλαγής κλινών η μεγαλύτερη απόκλιση διακρίνεται στο νοσοκομείο Γ.Ν.Α. "ΠΟΛΥΚΛΙΝΙΚΗ", όπου έχει τον υψηλότερο δείκτη και 20 κλίνες, στο Γ.Ν. ΕΛΕΥΣΙΝΑΣ "ΘΡΙΑΣΙΟ", με χαμηλό δείκτη και 393 κλίνες και στο Γ.Ν. ΒΕΡΟΙΑΣ με χαμηλότερο δείκτη και 801 κλίνες. Το διάστημα εναλλαγής κλινών επίσης είναι σχετικά παρόμοιο στα περισσότερα νοσοκομεία, με εξαίρεση δύο νοσοκομεία που παρουσιάζουν εντυπωσιακά υψηλό δείκτη. Αυτά είναι το Γ.Ν. ΔΥΤΙΚΗΣ ΑΤΤΙΚΗΣ με 58 κλίνες και υψηλό δείκτη και το Γ.Ν. ΑΜΑΛΙΑΔΑΣ, με 86 κλίνες και τον υψηλότερο δείκτη. Αυτό δηλώνει κακή χρήση των κρεβατιών.

Ακόμα, παρατηρείται έντονη διαφορά μεταξύ των δύο μαιευτικών νοσοκομείων με το Γ.Ν.Α. "ΑΛΕΞΑΝΔΡΑ" να έχει υψηλό ρυθμό εναλλαγής κλινών και χαμηλό διάστημα εναλλαγής κλινών. Σημειώνεται ότι έχει 430 κλίνες. Αντίθετα, το Γ.Ν. ΜΑΙΕΥΤΗΡΙΟ ΑΘΗΝΩΝ "ΕΛΕΝΑ ΒΕΝΙΖΕΛΟΥ" με 405 κλίνες παρουσιάζει χαμηλότερο δείκτη εναλλαγής κλινών και υψηλότερο δείκτη διαστήματος εναλλαγής κλινών. Συγκριτικά, το Γ.Ν.Α. "ΑΛΕΞΑΝΔΡΑ" είναι πιο αποδοτικό όσον αφορά τους συγκεκριμένους δείκτες.

Σχετικά με τα νοσοκομεία Παίδων, το νοσοκομείο Γ.Ν. ΠΑΙΔΩΝ "Η ΑΓΙΑ ΣΟΦΙΑ" παρουσιάζει ελαφρώς υψηλότερο δείκτη ρυθμού εναλλαγής κλινών από τα υπόλοιπα. Όσον αφορά όμως τον δείκτη διαστήματος εναλλαγής κλινών, τα νοσοκομεία Γ.Ν. ΠΑΙΔΩΝ "ΠΑΝ. & ΑΓΛ. ΚΥΡΙΑΚΟΥ" και Γ.Ν. ΠΑΙΔΩΝ ΠΕΝΤΕΛΗΣ παρουσιάζουν υψηλούς δείκτες υποδηλώνοντας πιθανώς μία κακή χρήση των διαθέσιμων κλινών. 

Συνεχίζοντας με τα Γ.Ν.-Κ.Υ, το Γ.Ν.-Κ.Υ. ΝΑΞΟΥ παρουσιάζει τον υψηλότερο δείκτη ρυθμού εναλλαγής και χαμηλότερο δείκτη διαστήματος εναλλαγής συγκριτικά με τα υπόλοιπα αντίθετα με το Γ.Ν.- Κ.Υ. ΓΟΥΜΕΝΙΣΣΑΣ. Σε γενικές γραμμές ωστόσο, πολλά νοσοκομεία αυτής της κατηγορίας παρουσιάζουν υψηλότερο δείκτη διαστήματος εναλλαγής κλινών από ότι ρυθμού εναλλαγής κλινών. 

Από τα λίγα ψυχιατρικά νοσοκομεία παρατηρούμε ότι το ΚΡΑΤΙΚΟ ΘΕΡΑΠΕΥΤΗΡΙΟ- Κ.Υ. ΛΕΡΟΥ παρουσιάζει χαμηλότερο ρυθμό εναλλαγής κλινών και υψηλότερο ρυθμό διαστήματος εναλλαγής κλινών. Τα υπόλοιπα ψυχιατρικά νοσοκομεία παρουσιάζουν μία πιο ομαλή λειτουργία. 

Η τελευταία κατηγορία που χρειάζεται ανάλυση σχετικά με τους συγκεκριμένους δείκτες είναι η κατηγορία των Πανεπιστημιακών νοσοκομείων. Την ομαλότερη λειτουργία από αυτά φαίνεται να την έχει το ΠΑΝΕΠΙΣΤΗΜΙΑΚΟ Γ.Ν. "ΑΤΤΙΚΟΝ" το οποίο παρουσιάζει υψηλό δείκτη ρυθμού εναλλαγής κλινών και αρνητικό δείκτη διαστήματος εναλλαγής κλινών. Αντίστοιχα ομαλή λειτουργία παρουσιάζει το ΠΑΝΕΠΙΣΤΗΜΙΑΚΟ Γ.Ν. ΠΑΤΡΩΝ για τους ίδιους λόγους. Τα νοσοκομεία ΠΑΝΕΠΙΣΤΗΜΙΑΚΟ Γ.Ν. "ΑΧΕΠΑ", ΠΑΝΕΠΙΣΤΗΜΙΑΚΟ Γ.Ν. ΑΛΕΞΑΝΔΡΟΥΠΟΛΗΣ και ΠΑΝΕΠΙΣΤΗΜΙΑΚΟ Γ.Ν. ΙΩΑΝΝΙΝΩΝ παρουσιάζουν υψηλό δείκτη διαστήματος εναλλαγής κλινών.

# Οικονομικοί Δείκτες 

## Μέσο Συνολικό Κόστος Ασθενή

Το μέσο συνολικό κόστος ασθενή δείχνει τα έξοδα του νοσοκομείου ανά ασθενή. Αυτό συμπεριλαμβάνει όλα τα κόστη, αλλά, όχι τις μισθοδοσίες.  

```{python}
cost = pd.read_excel('financial.xlsx', sheet_name = 'Μέσο κόστος για υπηρεσίες')

# Replace missing values with 'Unknown'
cost['ΚΑΤΗΓΟΡΙΑ ΝΟΣΟΚΟΜΕΙΟΥ'].fillna('Unknown', inplace = True)

# Group the data by hospital type
grouped_data = cost.groupby('ΚΑΤΗΓΟΡΙΑ ΝΟΣΟΚΟΜΕΙΟΥ')

# Get the unique hospital types
hospital_types = cost['ΚΑΤΗΓΟΡΙΑ ΝΟΣΟΚΟΜΕΙΟΥ'].unique()
hospital_types = hospital_types[hospital_types != 'Unknown']

# Create a subplot for each hospital type
fig, axs = plt.subplots(len(hospital_types), 1, figsize = (8, 6 * len(hospital_types)))

# Iterate over hospital types and create bar plots
for i, hospital_type in enumerate(hospital_types):
  data = grouped_data.get_group(hospital_type)
  ax = axs[i]
  ax.bar(data['ΝΟΣΟΚΟΜΕΙΑ'], data['Μέσο Συνολικό Κόστος Ασθενή'], color ='#9EBBC4')
  ax.set_title(f'Κατηγορία Νοσοκομείου: {hospital_type}')
  ax.set_xlabel('Νοσοκομείο')
  ax.set_ylabel('Μέσο Συνολικό Κόστος Ασθενή')
  ax.tick_params(axis = 'x', rotation = 90, labelsize = 6)  
# Adjust the layout
plt.tight_layout()

# Display the plot
plt.show()
```

Από την οπτικοποίηση παρατηρούμε ότι αναφορικά με τα Γενικά Νοσοκομεία παρουσιάζουν όλα εξαιρετικά χαμηλές τιμές γι’ αυτόν τον δείκτη, με εξαίρεση τρία νοσοκομεία. Αυτά είναι το Γ.Ν.Α. "Ο ΕΥΑΓΓΕΛΙΣΜΟΣ", το Γ.Ν. ΝΙΚΑΙΑΣ ΠΕΙΡΑΙΑ "ΑΓΙΟΣ ΠΑΝΤΕΛΕΗΜΩΝ" και το Γ.Ν. ΧΙΟΥ "ΣΚΥΛΙΤΣΕΙΟ". Έπειτα, παρατηρείται σχετικά μεγάλη διαφορά μεταξύ των μαιευτικών νοσοκομείων με το Γ.Ν. ΜΑΙΕΥΤΗΡΙΟ ΑΘΗΝΩΝ "ΕΛΕΝΑΣ ΒΕΝΙΖΕΛΟΥ" να έχει υψηλότερο δείκτη. 

Ακόμα, παρουσιάζεται αρκετά μεγάλη διαφορά μεταξύ των νοσοκομείων Παίδων. Συγκεκριμένα, παρουσιάζουν όλα πολύ χαμηλό δείκτη με εξαίρεση το Γ.Ν. ΠΑΙΔΩΝ ΠΕΝΤΕΛΗΣ. Στις υπόλοιπες κατηγορίες, οι διαφορές φαίνεται να είναι μικρότερες. Ωστόσο, παρατηρείται μία σχετική διαφορά ανάμεσα στα ογκολογικά νοσοκομεία ΓΕΝ. ΑΝΤΙΚΑΡΚΙΝΙΚΟ ΝΟΣΟΚΟΜΕΙΟ "ΑΓ. ΣΑΒΒΑΣ" και  ΑΝΤΙΚΑΡΚΙΝΙΚΟ ΝΟΣ. ΘΕΣ/ΝΙΚΗΣ "ΘΕΑΓΕΝΕΙΟ", με το πρώτο να παρουσιάζει τον υψηλότερο δείκτη και το τελευταίο τον χαμηλότερο. 

Συνεχίζοντας με τα Γ.Ν.-Κ.Υ. το Γ.Ν.- Κ.Υ. ΓΟΥΜΕΝΙΣΣΑΣ παρουσιάζει τον υψηλότερο δείκτη και το Γ.Ν.- Κ.Υ. ΚΡΕΣΤΕΝΩΝ τον χαμηλότερο. Εντυπωσιακά επίσης είναι τα αποτελέσματα για τα ψυχιατρικά νοσοκομεία καθώς όλα έχουν πολύ χαμηλό δείκτη πέρα από το ΨΥΧΙΑΤΡΙΚΟ ΝΟΣΟΚΟΜΕΙΟ ΑΤΤΙΚΗΣ. Στις υπόλοιπες κατηγορίες νοσοκομείων δεν παρουσιάζεται κάποια σημαντική απόκλιση.

## Μέσο Κόστος Υπηρεσιών ανά Ημέρα Νοσηλείας

Ο δείκτης αυτός δείχνει το κόστος των υπηρεσιών ανά ημέρα νοσηλείας. Οι υπηρεσίες αυτές είναι η ασφάλεια, η παροχή φαγητού, η καθαριότητα κ.α.. Σε περίπτωση που αυτός ο δείκτης είναι υψηλός, η λειτουργία ενός νοσοκομείου χρειάζεται επανεξέταση. 

```{python}
# Filter out the 'Unknown' category
hospital_types = cost['ΚΑΤΗΓΟΡΙΑ ΝΟΣΟΚΟΜΕΙΟΥ'].unique()
hospital_types = hospital_types[hospital_types != 'Unknown']

# Create a subplot for each hospital type
fig, axs = plt.subplots(len(hospital_types), 1, figsize = (8, 6 * len(hospital_types)))

# Group the data by hospital type
grouped_data = cost.groupby('ΚΑΤΗΓΟΡΙΑ ΝΟΣΟΚΟΜΕΙΟΥ')

# Iterate over hospital types and create bar plots
for i, hospital_type in enumerate(hospital_types):
    data = grouped_data.get_group(hospital_type)
    ax = axs[i]
    ax.bar(data['ΝΟΣΟΚΟΜΕΙΑ'], data['Μέσο Κόστος Υπηρεσιών ανά Ημέρα Νοσηλείας'], color ='#9EBBC4')
    ax.set_title(f'Κατηγορία Νοσοκομείου: {hospital_type}')
    ax.set_xlabel('Νοσοκομείο')
    ax.set_ylabel('Μέσο Κόστος Υπηρεσιών ανά Ημέρα Νοσηλείας')
    ax.tick_params(axis = 'x', rotation = 90, labelsize = 6)

# Adjust the layout
plt.tight_layout()

# Display the plot
plt.show()
```

Σχετικά με τα Γενικά νοσοκομεία, από την οπτικοποίηση παρατηρούμε ότι το Γ.Ν. ΑΜΑΛΙΑΔΑΣ έχει δραματικά υψηλότερα έξοδα σε σχέση με τα υπόλοιπα νοσοκομεία της ίδιας κατηγορίας. Επίσης υψηλούς δείκτες έχουν τα νοσοκομεία Γ.Ν. ΛΗΞΟΥΡΙΟΥ "ΜΑΝΤΖΑΒΙΝΑΤΕΙΟ", Γ.Ν. ΚΑΡΠΑΘΟΥ και Γ.Ν. "ΠΑΠΑΓΕΩΡΓΙΟΥ". Τα υπόλοιπα Γενικά νοσοκομεία έχουν παρόμοια αποτελέσματα. Αναφορικά με τα Μαιευτικά νοσοκομεία, φαίνεται και σε αυτή τη περίπτωση το Γ.Ν.Α. "ΑΛΕΞΑΝΔΡΑ" να λειτουργεί καλύτερα καθώς έχει αισθητά μικρότερο δείκτη. Τα νοσοκομεία των υπόλοιπων κατηγοριών παρουσιάζουν μεν διαφορές, αλλά οι δείκτες παραμένουν χαμηλοί.

## Συνολικό Ποσοστό Υπηρεσιών

Το συνολικό ποσοστό αποτελεί το ποσοστό των συνολικών εξόδων για τις υπηρεσίες. 

```{python}
# Filter out the 'Unknown' category
hospital_types = cost['ΚΑΤΗΓΟΡΙΑ ΝΟΣΟΚΟΜΕΙΟΥ'].unique()
hospital_types = hospital_types[hospital_types != 'Unknown']

# Create a subplot for each hospital type
fig, axs = plt.subplots(len(hospital_types), 1, figsize = (8, 6 * len(hospital_types)))

# Group the data by hospital type
grouped_data = cost.groupby('ΚΑΤΗΓΟΡΙΑ ΝΟΣΟΚΟΜΕΙΟΥ')

# Iterate over hospital types and create bar plots
for i, hospital_type in enumerate(hospital_types):
    data = grouped_data.get_group(hospital_type)
    ax = axs[i]
    ax.bar(data['ΝΟΣΟΚΟΜΕΙΑ'], data['Συνολικό Ποσοστό'], color = '#9EBBC4')
    ax.set_title(f'Κατηγορία Νοσοκομείου: {hospital_type}')
    ax.set_xlabel('Νοσοκομείο')
    ax.set_ylabel('Συνολικό Ποσοστό')
    ax.tick_params(axis = 'x', rotation = 90, labelsize = 6)
    ax.set_ylim(0, 1)  # Set the y-axis limits to 0-1 for percentage values
    # Set y-axis tick labels as percentages
    ax.yaxis.set_major_formatter('{x:.0%}')

# Adjust the layout
plt.tight_layout()

# Display the plot
plt.show()
```

Υλοποιώντας την οπτικοποίηση, παρατηρείται ότι τα περισσότερα Γενικά νοσοκομεία κυμαίνονται σε χαμηλά ποσοστά με εξαίρεση το Γ.Ν. "ΠΑΠΑΓΕΩΡΓΙΟΥ" του οποίο ο δείκτης είναι σχεδόν 50%. Στη συνέχεια, τα πανεπιστημιακά νοσοκομεία έχουν ελαφρώς αυξημένους δείκτες, ιδίως το ΠΑΝΕΠΙΣΤΗΜΙΑΚΟ Γ.Ν. ΗΡΑΚΛΕΙΟΥ. Οι υπόλοιπες κατηγορίες νοσοκομείων έχουν χαμηλούς δείκτες.

## Ποσοστό Συνολικών Εξωτερικών Υπηρεσιών

Ο δείκτης ποσοστό συνολικών εξωτερικών υπηρεσιών αναφέρεται στις Υπηρεσίες Εξωτερικής Ανάθεσης Σημαντικού Κόστους. Συγκεκριμένα, πρόκειται για τις υπηρεσίες που αναλαμβάνονται από τρίτους φορείς, όπως για παράδειγμα η ασφάλεια. 

```{python}
cost = pd.read_excel('financial.xlsx', sheet_name = 'Υπηρεσίες εξωτερικής ανάθεσης')

# Replace missing values with 'Unknown'
cost['ΚΑΤΗΓΟΡΙΑ ΝΟΣΟΚΟΜΕΙΟΥ'].fillna('Unknown', inplace = True)

# Group the data by hospital type
grouped_data = cost.groupby('ΚΑΤΗΓΟΡΙΑ ΝΟΣΟΚΟΜΕΙΟΥ')

# Get the unique hospital types
hospital_types = cost['ΚΑΤΗΓΟΡΙΑ ΝΟΣΟΚΟΜΕΙΟΥ'].unique()
hospital_types = hospital_types[hospital_types != 'Unknown']

# Create a subplot for each hospital type
fig, axs = plt.subplots(len(hospital_types), 1, figsize = (8, 6 * len(hospital_types)))

# Iterate over hospital types and create bar plots
for i, hospital_type in enumerate(hospital_types):
  data = grouped_data.get_group(hospital_type)
  ax = axs[i]
  ax.bar(data['ΝΟΣΟΚΟΜΕΙΑ'], data['Ποσοστό Συνολικών Εξωτερικών Υπηρεσιών'], color ='#9EBBC4')
  ax.set_title(f'Κατηγορία Νοσοκομείου: {hospital_type}')
  ax.set_xlabel('Νοσοκομείο')
  ax.set_ylabel('Ποσοστό Συνολικών Εξωτερικών Υπηρεσιών')
  ax.tick_params(axis = 'x', rotation = 90, labelsize = 6)  
  ax.set_ylim(0, 1)  # Set the y-axis limits to 0-1 for percentage values
  # Set y-axis tick labels as percentages
  ax.yaxis.set_major_formatter('{x:.0%}')
# Adjust the layout
plt.tight_layout()

# Display the plot
plt.show()
```

Από την υλοποίηση είναι εμφανές πως για τις περισσότερες κατηγορίες νοσοκομείων ο δείκτης αυτός είναι πολύ χαμηλός. Ωστόσο, ορισμένες κατηγορίες εμφανίζουν υψηλότερα ποσοστά. Αυτές είναι τα γενικά νοσοκομεία, τα ορθοπεδικά, τα ψυχιατρικά και τα πανεπιστημιακά. 

Όσον αφορά τα γενικά, κατά βάση ο δείκτης είναι χαμηλός (<= 20%), με εξαίρεση τα νοσοκομεία Γ.Ν. ΘΕΣ/ΝΙΚΗΣ "Γ. ΠΑΠΑΝΙΚΟΛΑΟΥ" και Γ.Ν. ΛΑΜΙΑΣ. Παρόλο που υπάρχουν τουλάχιστον τρία ακόμα νοσοκομεία με σχετικά υψηλότερους δείκτες από τα υπόλοιπα, αυτά τα δύο νοσοκομεία έχουν αρκετά υψηλότερο δείκτη και ιδίως το Γ.Ν. ΛΑΜΙΑΣ. 

Σχετικά με τα ορθοπεδικά νοσοκομεία, έχουν και αυτά έναν δείκτη <= 20%, όμως άλλες κατηγορίες έχουν δείκτη <=10%. 

Συνεχίζοντας με τα ψυχιατρικά νοσοκομεία, οι τιμή του δείκτη για το ΨΥΧΙΑΤΡΙΚΟ ΝΟΣΟΚΟΜΕΙΟ ΑΤΤΙΚΗΣ είναι περίπου ίση με 20% με το ΨΥΧΙΑΤΡΙΚΟ ΝΟΣΟΚΟΜΕΙΟ ΘΕΣΣΑΛΟΝΙΚΗΣ να έχει ελαφρώς χαμηλότερο δείκτη. Ωστόσο, το Ψ.Ν.Α. "ΔΡΟΜΟΚΑΪΤΕΙΟ" έχει αρκετά μικρότερο δείκτη από τα υπόλοιπα.

Τα πανεπιστημιακά νοσοκομεία, παρουσιάζουν τους υψηλότερους δείκτες και κυρίως το ΠΑΝΕΠΙΣΤΗΜΙΑΚΟ Γ.Ν. ΗΡΑΚΛΕΙΟΥ. Σχεδόν όλα τα πανεπιστημιακά νοσοκομεία έχουν δείκτη σχεδόν ίσο με 20% ή και περισσότερο. Το μοναδικό πανεπιστημιακό νοσοκομείο με μικρότερο δείκτη είναι το ΠΑΝΕΠΙΣΤΗΜΙΑΚΟ Γ.Ν. ΑΛΕΞΑΝΔΡΟΥΠΟΛΗΣ με τον δείκτη του να είναι λίγο υψηλότερος από 10%.


## Μέσο Μηνιαίο Κόστος των Εξωτερικών Υπηρεσιών ανά Κλίνη

Ο δείκτης Μέσο Μηνιαίο Κόστος των εξωτερικών Υπηρεσιών ανά Κλίνη αναφέρεται εξίσου στις Υπηρεσίες Εξωτερικής Ανάθεσης Σημαντικού Κόστους. 

```{python}
cost = pd.read_excel('financial.xlsx', sheet_name = 'Υπηρεσίες εξωτερικής ανάθεσης')

# Replace missing values with 'Unknown'
cost['ΚΑΤΗΓΟΡΙΑ ΝΟΣΟΚΟΜΕΙΟΥ'].fillna('Unknown', inplace = True)

# Group the data by hospital type
grouped_data = cost.groupby('ΚΑΤΗΓΟΡΙΑ ΝΟΣΟΚΟΜΕΙΟΥ')

# Get the unique hospital types
hospital_types = cost['ΚΑΤΗΓΟΡΙΑ ΝΟΣΟΚΟΜΕΙΟΥ'].unique()
hospital_types = hospital_types[hospital_types != 'Unknown']

# Create a subplot for each hospital type
fig, axs = plt.subplots(len(hospital_types), 1, figsize = (8, 6 * len(hospital_types)))

# Iterate over hospital types and create bar plots
for i, hospital_type in enumerate(hospital_types):
  data = grouped_data.get_group(hospital_type)
  ax = axs[i]
  ax.bar(data['ΝΟΣΟΚΟΜΕΙΑ'], data['Μέσο Μηνιαίο Κόστος των Εξωτερικών Υπηρεσιών ανά Κλίνη'], color = '#9EBBC4')
  ax.set_title(f'Κατηγορία Νοσοκομείου: {hospital_type}')
  ax.set_xlabel('Νοσοκομείο')
  ax.set_ylabel('Μέσο Μηνιαίο Κόστος των Εξωτερικών Υπηρεσιών ανά Κλίνη')
  ax.tick_params(axis = 'x', rotation = 90, labelsize = 6)  
# Adjust the layout
plt.tight_layout()

# Display the plot
plt.show()
```

Από την οπτικοποίηση του δείκτη για τα γενικά νοσοκομεία, παρατηρούμε ότι το εύρος του δείκτη ποικίλει. Υπάρχουν νοσοκομεία με αρκετά χαμηλό δείκτη, νοσοκομεία με μία ενδιάμεση τιμή και νοσοκομεία με υψηλό δείκτη. Τον υψηλότερο δείκτη τον έχουν τα "ΚΩΝΣΤΑΝΤΟΠΟΥΛΕΙΟ" Γ.Ν. ΝΕΑΣ ΙΩΝΙΑΣ, Γ.Ν. ΝΟΣΗΜΑΤΩΝ ΘΩΡΑΚΟΣ ΑΘΗΝΩΝ "ΣΩΤΗΡΙΑ", Γ.Ν. ΧΙΟΥ "ΣΚΥΛΙΤΣΕΙΟ", Γ.Ν. ΛΑΜΙΑΣ και Γ.Ν. ΛΗΞΟΥΡΙΟΥ "ΜΑΝΤΖΑΒΙΝΑΤΕΙΟ". Τα νοσοκομεία με τον χαμηλότερο δείκτη είναι τα Γ.Ν. "ΠΑΠΑΓΕΩΡΓΙΟΥ" και Γ.Ν. ΚΑΛΑΜΑΤΑΣ. Όσον αφορά τα ορθοπεδικά νοσοκομεία έχουν εύλογα υψηλό δείκτη. Έπειτα, σε σχέση με τα μαιευτικά νοσοκομεία, το Γ.Ν. ΜΑΙΕΥΤΗΡΙΟ ΑΘΗΝΩΝ "ΕΛΕΝΑΣ ΒΕΝΙΖΕΛΟΥ" έχει δείκτη μικρότερο από τον μισό του δείκτη του Γ.Ν.Α. "ΑΛΕΞΑΝΔΡΑ". Συγκρίνοντας τα νοσοκομεία Παίδων παρατηρείται πως η διαφορά στους δείκτες δεν είναι πολύ μεγάλη, όμως τα νοσοκομεία Γ.Ν. ΠΑΙΔΩΝ ΠΑΤΡΩΝ "ΚΑΡΑΜΑΝΔΑΝΕΙΟ" και Γ.Ν. ΠΑΙΔΩΝ "ΠΑΝ. & ΑΓΛ. ΚΥΡΙΑΚΟΥ" έχουν υψηλότερους δείκτες. Όσον αφορά το ογκολογικά νοσοκομεία υπάρχει μεγάλη απόκλιση ανάμεσα στα ΓΕΝ. ΑΝΤΙΚΑΡΚ. ΝΟΣ. ΠΕΙΡΑΙΑ "ΜΕΤΑΞΑ" και ΟΓΚΟΛ. ΝΟΣ. ΚΗΦΙΣΙΑΣ "ΟΙ ΑΓΙΟΙ ΑΝΑΡΓΥΡΟΙ" με τον πρώτο να έχει τον μεγαλύτερο δείκτη και το τελευταίο τον μικρότερο. Ακόμα, σχετικά υψηλός δείκτης παρατηρείται στα οφθαλμολογικά νοσοκομεία. Αναφορικά με τα Γ.Ν.-Κ.Υ., παρουσιάζονται μεγάλες διαφορές ανάμεσα στους δείκτες με το Γ.Ν.- Κ.Υ. ΦΙΛΙΑΤΩΝ να έχει τον υψηλότερο και το Γ.Ν.- Κ.Υ. ΚΡΕΣΤΕΝΩΝ να έχει τον μικρότερο. Μεγάλη απόκλιση μεταξύ των δεικτών παρουσιάζεται και στα Πανεπιστημιακά νοσοκομεία. Συγκεκριμένα, το νοσοκομείο ΠΑΝΕΠΙΣΤΗΜΙΑΚΟ Γ.Ν. "ΑΤΤΙΚΟΝ" έχει αρκετά υψηλό δείκτη. Στα υπόλοιπα νοσοκομεία οι τιμές του δείκτη είναι φυσιολογικές.

## Μέσο Κόστος των Εξωτερικών Υπηρεσιών ανά Ασθενή

Ο δείκτης Μέσο Κόστος Εξωτερικών Υπηρεσιών ανά Ασθενή αφορά και αυτός στις Υπηρεσίες Εξωτερικής Ανάθεσης Σημαντικού Κόστους. 

```{python}
cost = pd.read_excel('financial.xlsx', sheet_name = 'Υπηρεσίες εξωτερικής ανάθεσης')

# Replace missing values with 'Unknown'
cost['ΚΑΤΗΓΟΡΙΑ ΝΟΣΟΚΟΜΕΙΟΥ'].fillna('Unknown', inplace = True)

# Group the data by hospital type
grouped_data = cost.groupby('ΚΑΤΗΓΟΡΙΑ ΝΟΣΟΚΟΜΕΙΟΥ')

# Get the unique hospital types
hospital_types = cost['ΚΑΤΗΓΟΡΙΑ ΝΟΣΟΚΟΜΕΙΟΥ'].unique()
hospital_types = hospital_types[hospital_types != 'Unknown']

# Create a subplot for each hospital type
fig, axs = plt.subplots(len(hospital_types), 1, figsize = (8, 6 * len(hospital_types)))

# Iterate over hospital types and create bar plots
for i, hospital_type in enumerate(hospital_types):
  data = grouped_data.get_group(hospital_type)
  ax = axs[i]
  ax.bar(data['ΝΟΣΟΚΟΜΕΙΑ'], data['Μέσο Κόστος των Εξωτερικών Υπηρεσιών ανά Ασθενή'], color = '#9EBBC4')
  ax.set_title(f'Κατηγορία Νοσοκομείου: {hospital_type}')
  ax.set_xlabel('Νοσοκομείο')
  ax.set_ylabel('Μέσο Κόστος των Εξωτερικών Υπηρεσιών ανά Ασθενή')
  ax.tick_params(axis = 'x', rotation = 90, labelsize = 6)  
# Adjust the layout
plt.tight_layout()

# Display the plot
plt.show()
```

Από την οπτικοποίηση οι κατηγορίες νοσοκομείων που παρουσιάζουν ενδιαφέρον είναι τα γενικά, των Παίδων και τα ψυχιατρικά. Αυτό γατί διακρίνονται από υψηλούς δείκτες. Συγκεκριμένα, τα γενικά νοσοκομεία Γ.Ν. ΧΙΟΥ "ΣΚΥΛΙΤΣΕΙΟ" και Γ.Ν.Α. "Ο ΕΥΑΓΓΕΛΙΣΜΟΣ", είναι τα μόνα που παρουσιάζουν αυτόν τον δείκτη και ιδίως στο πρώτο νοσοκομείο είναι πολύ υψηλός. Σχετικά με τα νοσοκομεία Παίδων παρουσιάζεται πολύ υψηλός δείκτης μόνο στο Γ.Ν. ΠΑΙΔΩΝ ΠΕΝΤΕΛΗΣ. Τέλος, αναφορικά με τα ψυχιατρικά νοσοκομεία, το νοσοκομείο ΨΥΧΙΑΤΡΙΚΟ ΝΟΣΟΚΟΜΕΙΟ ΑΤΤΙΚΗΣ έχει πολύ υψηλό δείκτη, ενώ παράλληλα είναι και το μοναδικό που παρουσιάζει αυτόν τον δείκτη.